### ISSUE TITLE
Explorar cómo se usa la API de Food Inspections y generar token

### ISSUE THREAD

**Issue by caroacostatovany** [caroacostatovany/food_inspection_DPA#1]
Para poder ingestar estos datos a través de la API tendrás que generar un token, la explicación de cómo generar este token viene en la documentación https://dev.socrata.com/foundry/data.cityofchicago.org/4ijn-s7e5

**Comment by Eduardo-Moreno** [comment]
Token generado exitosamente (pedir a @Eduardo-Moreno compartir Token para este proyecto)

**Comment by Eduardo-Moreno** [comment]
Issue completado!!! :)
