### ISSUE TITLE
En src/pipeline agregar ingesta_almacenamiento.py

### ISSUE THREAD

**Issue by caroacostatovany** [caroacostatovany/food_inspection_DPA#4]
Este script debe tener las siguientes funciones:

- [x] get_client: Esta función regresa un cliente que se puede conectar a la API de inspecciones de establecimiento dándole un token previamente generado.

- [x] ingesta_inicial: Esta función recibe como parámetros el cliente con el que nos podemos comunicar con la API, y el límite de registros que queremos obtener al llamar a la API. Regresa una lista de los elementos que la API regresó.

- [x] get_s3_resource: Esta función regresa un resource de S3 para poder guardar datos en el bucket (checar script de aws_boto_s3).

- [x] guardar_ingesta: Esta función recibe como parámetros el nombre de tu bucket de S3, la ruta en el bucket en donde se guardarán los datos y los datos ingestados en csv.

- [x] ingesta_consecutiva: Esta función recibe como parámetros el cliente con el que nos podemos comunicar con la API, la fecha de la que se quieren obtener nuevos datos al llamar a la API y el límite de registros para obtener de regreso.

**Comment by caroacostatovany** [comment]
Aquí tengo una función que supongo nos puede servir después 

def read_pkl_from_s3(s3, buket_name, filename):
    """
    s3: el cliente de la sesión
    bucket_name: el nombre del bucket a entrar
    filename: el archivo .pkl que queremos leer
    """
    response = s3.get_object(
        Bucket=bucket_name,
        Key=filename)
    pkl_file = pickle.loads(response['Body'].read())
    return pkl_file

**Comment by Eduardo-Moreno** [comment]
He subido las funciones, faltará la prueba de las mismas

**Comment by Eduardo-Moreno** [comment]
Issue completado! :)
