### ISSUE TITLE
Crear un Bastión y crear usuarios

### ISSUE THREAD

**Issue by caroacostatovany** [caroacostatovany/food_inspection_DPA#8]
| usuario | llave pública |
|----------|----------|
| lmillan | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDxZhHbKTzK0z4TGa01g14PgARYsGsOYexkBpzb5w329LIwE0mJQISoORHdk0OTuCRvqpPBbJKFktdcy2rGZVmxeKAthldHCEkdRumhJswIjE22b2EHoKr1qRA950MlawasmUkAzVDgkfynNgRV28O+nT9xAx2yLEvtDxaJM4M2Xq6OOv/x0Pa3yoktKz8vXtlDsc4V+1RfYEg2xl4uGjLumSEzzgAa86OSk1qxjsAMoF+hBwbPdq/LSwLarO3XUdjWtbfI2TXjQHs1oTwtrHqC5fEq+vy2P+B29KjFITcP7NbvHXg7WONFj2SplDyuzgfrSmpIjzMPpc396rkOHoDwSDRau8NvO+srfbhEgAS92HmXpk/PFMHsOcJlzJXjXJBh6FmvKEp3RX2AB4H0NeXaCARUcXUUvsez62stDSUw/NxotwUcQhrApcWcVaokA2tVRsabilDzTePX17LAujJU0+l9ahfEeABl76B6t4rpW+t5jpLjVHFBT9auHM9Pk4c= silil@turing |
| tovany| ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+a23ltEseK4JGJRM9lJSiVocjWKsO5jv4yBMm+69YWhD8pikwHXBFbceGgdG/I6HHlNEghQ2W4o6V/cqQ1G+U/0wR/+bvxml62pUqn4SXqXg+Hp4IiXlWp2Xt24nXmDhQERBU87y+GPDvN0OXNTShK64QMRmssmOkIOKxqKfLXeXtNXyDnfFeXMo3q99LX0/6m3n2XiS86/QvfJkyxUAWxD/DkOaGsreLC+/q//xPO+wEg4B3X4yMp5fpwzy3f+Axk9bcmHElfyB6z2x0Ht/ScosZ33vtHBHLjGFrBZuTjKZstJS+XUoZYmT3+BbE8OG1AcN8X9C/Xe4SFs2BKgov user@user-Inspiron-15-7000-Gaming |
| caviles | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfzJPgWx9pQyCEe8YxvjxhHJ9d5eAcB/9nsfVYrey1ELD2QlqGQ6Y5iEFRsvnBdfSHS2d6aA0o54xACk4qKkV12rxU2ViwUSjaGe5ojWTKKeAk6M7ZZZnl4qZEUhrWQVrC+2VMbIwZDkxleN0qX/+VC04kbXo3/70t+DRmcuNFKfwsPwG/1s/Yc6rxx0gkdndtgDOQ2BF9wDNSReL+9Wz/Whq3x2d+fqcYIp4rvclzAQiPHbipE4LkUqdyCj5B1C/VPIBgyPmX8gcoy2kVHMss8oM05+t4bQSLkO2UmQSgsN2S4Pk4oOkMrXEcXYT4n6HUw7clNOq7U3xgDQnx/hn656H2uM6K/QoUWOcJSL9FYmiXlcg6Jq/cll2B5ApsCzlnU5j/gvlO4dzcI5ryyeNppQjnDvsDQXCZXWNiipnkF6LTJwjRv8tzeQ9oRl9JMpPTuQF0nshPMH9pNUt7ToFwSdZ4dDq6tgomb4if08hCwdhuJ4A2lyK4WceBb/WWsQU= cecy@Cecys-MacBook-Air.local | 
| lceja | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcJuSIh3cB00RdwxI+mDomG71YW+L1ZlpNBU83C9t2UirVNWukLJx+xUgHErO8HRQJJAcRDHlbKzHDDfKXN+ZRhJHBk8NL+QD8SeYjCXZ38IaMyi0DILZihR9Z3OyZMdt6jjWZwvEx+VHDeXPGBCeSPQUIkGPbEGSEbexiS+f9NCZCL6aVO+i1+n5mAu8yjDitKMuQZYcaWiqA/KQReKwNRzTXsegXee9RLSotEzZxHFWNz94XgwTEyNSKe8rn0XkQ/oJmB65YkUA0PrUQXuIHY1wypROFVsQO6P9Ok084By3hOEOS9eHwPr/7QjlxgIIMW0ufLCbc6vYWA+ZBgjX0pn7LzmAe8bJNq92Lm8i2b4YvCjT5aP3eexZ/J6NzYA/S6No85dvF9pTueUUTsD3g9pYkcEnuBHwY5Bs5OjUgQa5NDGvseqIb9gJZsY8SkZ920ym2S/5MvgYiZFalheUMTXVDKEK8lKyzOHhLGAmMnI0a8bxprqAqQdJaUh33kfc= Leo@MacBook-Pro-de-Leonardo.local |
| emoreno | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjxWI3gihDV2nwBGTxmBTN/hTBPvndEh2uYcBqWzcXvg30U9PHyW2Y4cgrOQhV8yD/wSuJSbO/ql0EQ+znbXL2+ok4/YlLQHyktkl7cU9RF1BMz/AeX3kdStLBChib0ATfG4zL48CrCj3METVFK/Smh5KO0CjhJUU/JBs2yMoIK8oT7rK0h7XYOPBldyJhXgag9DSkq9x4utJ3e3mpPawaxaO5phiWtVQOkeWGymZBemiAZKPyGJl0v9RGSQvETPifJpVXM/nIOOP28YoOxKAqxwOzLZIm3SyEgSAnHXJHtnpSsTa/efMRbP2yjLukg2QoDllIO66PZb5h0jr0njHD eduardomorenoortiz@MacBook-Air-de-Eduardo-5.local |

**Comment by cecyar** [comment]
Bastión creado con los usuarios enlistados arriba y revisado por Liliana
![image](https://user-images.githubusercontent.com/66655647/108651297-1532f480-7487-11eb-825a-04fed2cce918.png)
